development:
  adapter: postgresql
  encoding: unicode
  database: blog_app_dev
  pool: 5
  username: postgres
  password: 102110

test:
  adapter: postgresql
  encoding: unicode
  database: blog_app_testing
  pool: 5
  username: postgres
  password: 102110

production:
  adapter: postgresql
  encoding: unicode
  database: blog_app_prod
  pool: 5
  username: postgres
  password: 102110
