development:
  adapter: postgresql
  encoding: unicode
  database: blog_application_dev
  pool: 5
  username: sholotanyusuf
  password: 102110

test:
  adapter: postgresql
  encoding: unicode
  database: blog_application_testing
  pool: 5
  username: sholotanyusuf
  password: 102110

production:
  adapter: postgresql
  encoding: unicode
  database: blog_application_prod
  pool: 5
  username: sholotanyusuf
  password: 102110
